### ISSUE TITLE
Blog searches return plaintext article snippets

### ISSUE THREAD

**Issue by MayImilae** [dolphin-emu/www#33]
Pointed out by David3k on the IRC.

Running a search on the mainsite's blog returns the resulting blog post snippets as plain text. See the attached image for a demonstration. Also, click the following link to see it for yourself: https://dolphin-emu.org/blog/search/?pattern=jitil

Reproduced in Chrome and Safari.

![screen-shot-2015-04-05-at-2 43 02-am](https://cloud.githubusercontent.com/assets/6551020/6996212/1421628a-db3f-11e4-8a19-b95ca5d2f74f.png)

**Comment by Tilka** [comment]
This is because [our blog entry template](https://github.com/dolphin-emu/www/blob/master/dolweb/blog/templates/zinnia/_entry_detail_base.html#L52) doesn't use `|safe` as [the original](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templates/zinnia/_entry_detail_base.html#L81) does. No idea why.

**Comment by MaJoRoesch** [comment]
The snippets on facebook are in plaintext as well, come to think of it...

**Comment by Dentomologist** [comment]
This was fixed at some point, I believe by https://github.com/dolphin-emu/www/commit/1722ede4684e5175d2c5955dba6a6210de9029f6.
